{
 "title": "Atlantis",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(kube_namespace_labels{exported_namespace=\"atlantis-system\"},cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(atlantis_project_plan_execution_success,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "${clusterName}",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<p style=\"text-align:center; margin-left:auto; margin-right: auto; width: 70%\">\n  <img src=\"https://www.runatlantis.io/hero.png\">\n</p>"
   }
  },
  {
   "title": "Projects Count",
   "type": "stat",
   "description": "Shows current Atlantis project count",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(count by (project) (increase(atlantis_project_plan_execution_success{pod=~\"$instance\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Builder Projects ",
   "type": "stat",
   "description": "Shows total number of builders executed on all projects",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(atlantis_builder_projects{pod=~\"$instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GitHub Event Success",
   "type": "stat",
   "description": "Shows the total number of GitHub Events that have been successfully executed",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(atlantis_github_event_success_200{pod=~\"$instance\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Autoplan Execution Time",
   "type": "stat",
   "description": "Amount in minutes of total execution by autoplan",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(atlantis_cmd_autoplan_execution_time_sum{pod=~\"$instance\"}[$__interval]) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Plan Execution Time",
   "type": "stat",
   "description": "Shows the total time running plan in projects",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(atlantis_project_plan_execution_time_sum{pod=~\"$instance\"}[$__interval])) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Builder Executions",
     "type": "stat",
     "description": "Show builder execution count",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(atlantis_builder_execution_success{pod=~\"$instance\"}[$__interval])",
       "legendFormat": "Success"
      },
      {
       "expr": "increase(atlantis_builder_execution_error{pod=~\"$instance\"}[$__interval])",
       "legendFormat": "Failures"
      }
     ]
    },
    {
     "title": "Get Pull Request",
     "type": "stat",
     "description": "Shows the count of events related to getting Pull Request Execution",
     "gridPos": { "h": 7, "w": 4, "x": 3, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(atlantis_github_get_pull_request_execution_success{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(increase(atlantis_github_get_pull_request_execution_error{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "Failures"
      }
     ]
    },
    {
     "title": "GitHub Update Status",
     "type": "stat",
     "description": "Shows the count of GitHub update status events",
     "gridPos": { "h": 7, "w": 3, "x": 7, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(atlantis_github_update_status_execution_success{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(increase(atlantis_github_update_status_execution_error{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "Failures"
      }
     ]
    },
    {
     "title": "GitHub Modified Files",
     "type": "stat",
     "description": "Shows the count of GitHub events to get modified files",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(atlantis_github_get_modified_files_execution_success{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(increase(atlantis_github_get_modified_files_execution_error{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "Error"
      }
     ]
    },
    {
     "title": "GitHub Hide Prev Plan",
     "type": "stat",
     "description": "Show GitHub event count to hide prev plan",
     "gridPos": { "h": 7, "w": 3, "x": 14, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(atlantis_github_hide_prev_plan_comments_execution_success{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(increase(atlantis_github_hide_prev_plan_comments_execution_error{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "Error"
      }
     ]
    },
    {
     "title": "Project Plan Execution",
     "type": "stat",
     "description": "Shows the count of running plan in projects",
     "gridPos": { "h": 7, "w": 4, "x": 17, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(atlantis_project_plan_execution_success{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(increase(atlantis_project_plan_execution_failure{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "Failures"
      },
      {
       "expr": "sum(increase(atlantis_project_plan_execution_error{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "Error"
      }
     ]
    },
    {
     "title": "Pull Closed Cleanup",
     "type": "stat",
     "description": "Shows the count of execution events related to closed pull cleanup.",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(atlantis_pullclosed_cleanup_execution_success{pod=~\"$instance\"}[$__interval])",
       "legendFormat": "Success"
      },
      {
       "expr": "increase(atlantis_pullclosed_cleanup_execution_error{pod=~\"$instance\"}[$__interval])",
       "legendFormat": "Error"
      },
      {
       "expr": "increase(atlantis_pullclosed_cleanup_execution_time_sum{pod=~\"$instance\"}[$__interval]) / 60",
       "legendFormat": "Time"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Runtime Memory Total",
     "type": "timeseries",
     "description": "Scheduled runtime memory total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "increase(atlantis_scheduled_runtime_memory_total[$__interval]) / 1024^2",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Runtime Memory Stats",
     "type": "timeseries",
     "description": "Shows the grouped memory usage of alloc, frees and sys.\n\nSys is the total bytes of memory obtained from the OS.\n\nFrees is the cumulative count of heap objects freed.\n\nAlloc is bytes of allocated heap objects.\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "atlantis_scheduled_runtime_memory_alloc / 1024^2",
       "legendFormat": "alloc"
      },
      {
       "expr": "atlantis_scheduled_runtime_memory_frees / 1024^2",
       "legendFormat": "frees"
      },
      {
       "expr": "atlantis_scheduled_runtime_memory_sys / 1024^2",
       "legendFormat": "sys"
      }
     ]
    },
    {
     "title": "Runtime Memory Heap",
     "type": "timeseries",
     "description": "Shows the grouped heap memory usage.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "atlantis_scheduled_runtime_memory_heap_alloc / 1024^2",
       "legendFormat": "heap alloc"
      },
      {
       "expr": "atlantis_scheduled_runtime_memory_heap_idle / 1024^2",
       "legendFormat": "heap idle"
      },
      {
       "expr": "atlantis_scheduled_runtime_memory_heap_inuse / 1024^2",
       "legendFormat": "heap in use"
      },
      {
       "expr": "atlantis_scheduled_runtime_memory_heap_released / 1024^2",
       "legendFormat": "heap released"
      },
      {
       "expr": "atlantis_scheduled_runtime_memory_heap_sys / 1024^2",
       "legendFormat": "heap sys"
      }
     ]
    },
    {
     "title": "Disc Usage (GiB)",
     "type": "timeseries",
     "description": "Show the disc usage",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "GiB" } },
     "targets": [
      {
       "expr": "sum(avg_over_time(kubernetes_io:pod_volume_used_bytes{monitored_resource=\"k8s_pod\", pod_name=~\"$instance\",metadata_system_top_level_controller_name=\"atlantis\"}[${__interval}])) / 1024^3",
       "legendFormat": "usage"
      },
      {
       "expr": "sum(avg_over_time(kubernetes_io:pod_volume_total_bytes{monitored_resource=\"k8s_pod\",\npersistentvolumeclaim_name=\"atlantis-data\", pod_name=~\"$instance\", \nmetadata_system_top_level_controller_name=\"atlantis\"}[${__interval}])) / 1024^3",
       "legendFormat": "capacity"
      }
     ]
    }
   ]
  },
  {
   "title": "Projects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Projects",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "group by (project, project_path, workspace) (increase(atlantis_project_plan_execution_success{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PRs Opens",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "group by (base_repo, pr_number) (atlantis_github_create_comment_execution_time_sum)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GitHub Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "PR Events (aggregated)",
     "type": "timeseries",
     "description": "It shows the number of GitHub events grouped.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(increase(atlantis_github_event_comment_created_success_200{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "Comment Created"
      },
      {
       "expr": "sum(increase(atlantis_github_event_pr_synchronize_success_200{pod=~\"$instance\"}[$__interval]) )",
       "legendFormat": "PR Synchronize"
      },
      {
       "expr": "sum(increase(atlantis_github_event_pr_assigned_success_200{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "PR Assigned"
      },
      {
       "expr": "sum(increase(atlantis_github_event_pr_closed_success_200{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "PR Closed"
      },
      {
       "expr": "sum(increase(atlantis_github_event_pr_edited_success_200{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "PR Edited"
      },
      {
       "expr": "sum(increase(atlantis_github_event_pr_labeled_success_200{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "PR Labeled"
      },
      {
       "expr": "sum(increase(atlantis_github_event_pr_opened_success_200{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "PR Opened"
      },
      {
       "expr": "sum(increase(atlantis_github_event_pr_review_requested_success_200{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "PR Review Requested"
      }
     ]
    },
    {
     "title": "Comment Created",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "increase(atlantis_github_event_comment_created_success_200{pod=~\"$instance\"}[$__interval])",
       "legendFormat": "PR Number: {{pr_number}}"
      }
     ]
    },
    {
     "title": "PR Opened",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "increase(atlantis_github_event_pr_opened_success_200{pod=~\"$instance\"}[$__interval]) ",
       "legendFormat": "PR Number: {{pr_number}}"
      }
     ]
    },
    {
     "title": "PR Assigned",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "increase(atlantis_github_event_pr_assigned_success_200{pod=~\"$instance\"}[$__interval])",
       "legendFormat": "PR Number: {{pr_number}}"
      }
     ]
    },
    {
     "title": "PR Labeled",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "increase(atlantis_github_event_pr_labeled_success_200{pod=~\"$instance\"}[$__interval]) ",
       "legendFormat": "PR Number: {{pr_number}}"
      }
     ]
    },
    {
     "title": "PR Edited",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "increase(atlantis_github_event_pr_edited_success_200{pod=~\"$instance\"}[$__interval]) ",
       "legendFormat": "PR Number: {{pr_number}}"
      }
     ]
    },
    {
     "title": "PR Closed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "increase(atlantis_github_event_pr_closed_success_200{pod=~\"$instance\"}[$__interval])",
       "legendFormat": "PR Number: {{pr_number}}"
      }
     ]
    },
    {
     "title": "PR Review Requested",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "increase(atlantis_github_event_pr_review_requested_success_200{pod=~\"$instance\"}[$__interval]) ",
       "legendFormat": "PR Number: {{pr_number}}"
      }
     ]
    },
    {
     "title": "PR Synchronize",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "increase(atlantis_github_event_pr_synchronize_success_200{pod=~\"$instance\"}[$__interval]) ",
       "legendFormat": "PR Number: {{pr_number}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GitHub Pull Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pull Request Execution Time",
     "type": "timeseries",
     "description": "Show the breakdown total execution time in GitHub events",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(atlantis_github_pull_is_approved_execution_time_sum{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "pull is approved "
      },
      {
       "expr": "sum(increase(atlantis_github_pull_is_mergeable_execution_time_sum{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "pull is mergeable"
      }
     ]
    },
    {
     "title": "GitHub Update Status Time",
     "type": "timeseries",
     "description": "GitHub Event Update status breakdown by Pull request number",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pr_number) (increase(atlantis_github_update_status_execution_time_sum{pod=~\"$instance\"}[$__interval]))",
       "legendFormat": "PR - {{pr_number}}"
      }
     ]
    }
   ]
  }
 ]
}